# Generated by Django 3.2.3 on 2021-07-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='imageBack',
            field=models.ImageField(default='1.jpg', upload_to='static'),
        ),
    ]
