# Generated by Django 3.2 on 2021-04-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Game name', max_length=100)),
                ('description', models.TextField(help_text='Description about game', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idName', models.CharField(help_text='Enter Game Genre url id', max_length=100)),
                ('name', models.CharField(help_text='Enter Game Genre name', max_length=100)),
                ('description', models.TextField(help_text='Description about game genre', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games\\<django.db.models.fields.related.ForeignKey>')),
                ('nameGame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameGenre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gamegenre'),
        ),
    ]
